### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Million900o**
Making the cute function static so it can be used without creating a new Lumap.

### CODE REVIEW

**Comment by TheNoob27** [comment]
make it both, because lumap is cute on the inside AND the outside

**Comment by vierofernando** [comment]
pog

**Comment by Million900o** [comment]
I don't see how we can make it static and non-static.

**Comment by TheNoob27** [comment]
```js
class Lu extends Map {
  static cute() {
    return true;
  }

  cute() {
    return true;
  }
}

module.exports = Lu;
```

**Comment by vierofernando** [comment]
that's nice

**Comment by Million900o** [comment]
> ```js
> class Lu extends Map {
>   cute() {
>     return true;
>   }
> 
>   static cute() {
>     return true;
>   }
> }
> 
> module.exports = Lu;
> ```

Won't this just be the same as doing one static?

**Pull request merged**
